version: '3.3'

services:
  # aqui cria
  db: # container de mysql
    image: mysql:5.7 # mesma coisa de FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always # todas as alterações que eu fizer no arquivo serão atualizadas automaticamente
    env_file:
      - ./config/db.env
 
  # aqui acessa
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: "always"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: matheus
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
volumes: 
  db_data: {} # compose inicia algum volume pra aplicação