version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3307"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on: 
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    # bind mount
    volumes:
      - "C:\\Users\\roberta.carvalho\\Documents\\Docker\\Compose\\Bind_mount\\flask:/app"
    networks: 
      - dockercompose

networks:
  dockercompose: